### ISSUE TITLE
 No module named 'flightning.envs.simple_hovering_env'

### ISSUE THREAD

**Issue by zhw970623** [uzh-rpg/rpg_flightning#2]
/home/zhw/miniconda3/envs/flightning/bin/python /home/zhw/reach/rpg_flightning/flightning/algos/bptt.py
Traceback (most recent call last):
  File "/home/zhw/reach/rpg_flightning/flightning/algos/bptt.py", line 161, in <module>
    from flightning.envs.simple_hovering_env import SimpleHoveringEnv
ModuleNotFoundError: No module named 'flightning.envs.simple_hovering_env'

Check the project structure. In the flightning/envs/ directory, there are:
hovering_features_env.py
hovering_state_env.py
env_base.py
wrappers.py

But there is no simple_hovering_env.py file.

**Comment by joheeg** [comment]
Thanks for pointing out.
