### ISSUE TITLE
Custom JVP rule, drone configs

### ISSUE THREAD

**Issue by cmakelabs** [uzh-rpg/rpg_flightning#3]
Thank you very much for sharing flightning!
I have installed it successfully, however, when trying to run the notebook `train_bptt_vision.ipynb`, I got the following error:

```
File [~/miniconda3/envs/flightning/lib/python3.13/site-packages/jax/_src/custom_derivatives.py:351](http://localhost:8888/home/user/miniconda3/envs/flightning/lib/python3.13/site-packages/jax/_src/custom_derivatives.py#line=350), in _flatten_jvp(primal_name, jvp_name, in_tree, maybe_out_type, *args)
    344     msg = ("Custom JVP rule must produce primal and tangent outputs with "
    345            "corresponding shapes and dtypes, but got:\n{}")
    346     disagreements = (
    347         f"  primal {av_p.str_short()} with tangent {av_t.str_short()}, expecting tangent {av_et}"
    348         for av_p, av_et, av_t in zip(primal_avals_out, expected_tangent_avals_out, tangent_avals_out)
    349         if av_et != av_t)
--> 351     raise TypeError(msg.format('\n'.join(disagreements)))
    352 yield primals_out + tangents_out, (out_tree, primal_avals)

TypeError: Custom JVP rule must produce primal and tangent outputs with corresponding shapes and dtypes, but got:
  primal key<fry>[] with tangent key<fry>[], expecting tangent ShapedArray(float0[])
```

It's important to note, that in the original notebook the quadrotor object configuration was specified as `kolibri.yaml`, but since I couldn't find this file in the flightning repo, I have used `example_quad.yaml` as it is the only quadrotor configuration available. May you please guide me on how to debug this issue properly and resolve it? And would be really grateful if you could tell how to obtain the values for the configuration file of the drone.

Your guidance is highly appreciated.

**Comment by joheeg** [comment]
Thanks for reaching out. `example_quad.yaml` is correct. Regarding the TypeError, it might be related to this issue here: https://github.com/jax-ml/jax/discussions/24262 . If you are using jax 0.4.34, try using 0.4.33.
